#docker run -p 8081:4200 angular-front-start:V1


#FROM node:16.13.0
FROM node:16-alpine3.13

WORKDIR /app/front

#COPY    ./angular-cli .
COPY package.json package-lock.json
COPY . .

RUN npm install
RUN npm install -g @angular/cli

EXPOSE  4200
# Angular installation if it fails,

CMD ["ng", "serve", "--host", "0.0.0.0"]
