FROM node:16.13.0

WORKDIR /app/front

#COPY    ./angular-cli .
COPY package.json package-lock.json
COPY . .

RUN npm install
RUN npm install -g @angular/cli

EXPOSE  8081
# Angular installation if it fails,

CMD ["ng", "serve", "--host", "0.0.0.0"]
